### ISSUE TITLE
Hardcoded texts

### ISSUE THREAD

**Issue by turbostar190** [stijnwop/hoseSystem#13]
The function `MouseHelper.getButtonName(Input.MOUSE_BUTTON_RIGHT)` and `MouseHelper.getButtonName(Input.MOUSE_BUTTON_LEFT)` return only english words "right" and "left".
Should be checked and translated depending the language?

![fsscreen_2017_10_28_21_13_07_li](https://user-images.githubusercontent.com/24813315/32137820-833b5bdc-bc27-11e7-8616-f125aeefcfd4.jpg)

**Comment by stijnwop** [comment]
I will add the translation to the xml file. ;)

Also got a report in a different pull request. (https://github.com/stijnwop/hoseSystem/pull/12)

**Comment by stijnwop** [comment]
Commited a fix, but it needs a translation update. 

@turbostar190 @n0tr3adY
