### ISSUE TITLE
Question and suggestion regarding translation

### ISSUE THREAD

**Issue by KITT3000** [stijnwop/hoseSystem#18]
1) Question:
Could you describe more accurately when a warning appears, or is it related to the same condition (pump source is empty)?
`pumpMotor_warningUnitEmpty`
`pumpMotor_warningObjectEmpty`
2) Suggestion:
If you add a new translation you could do it this way for each XML file?
`<text name="input_mouseInteractMouseLeft" text="left"/> <!-- TODO TRANSLATION: description-->`
(text in English to be translated + description for better understanding of the translated text)

**Comment by stijnwop** [comment]
1. pumpMotor_warningUnitEmpty = when the fill unit of your vehicle is empty (in FS17 your vehicle can hold multiple fill units).
pumpMotor_warningObjectEmpty = when the fillLevel of the source object is empty.

2. Yeah wonder why i didn't do that last time. Well, will do it that way in the future. ;)

**Comment by KITT3000** [comment]
Ok, thanks for the explanation ;)
