### ISSUE TITLE
Never Ending Synchronisation on Dedicated Server

### ISSUE THREAD

**Issue by DieModdingecke** [stijnwop/hoseSystem#19]
If i try to join my server, i get this error 

Error: Running LUA method 'update'.
C:/Users/Jannis/Documents/My Games/FarmingSimulator2017/mods/FS17_hoseSystem_DEV/specializations/HoseSystemPlayerInteractiveHandling.lua:44: attempt to index field 'player' (a nil value)

and the synchronisation is never ending.

Hope you´ve got a solution ;)

**Comment by stijnwop** [comment]
On what map are you playing? Want to know if any other scripts are conflicting.

Because when we can't access the player table (like the log says) something else it doing something dirty with it.. I wonder why.

**Comment by DieModdingecke** [comment]
[log.txt](https://github.com/stijnwop/hoseSystem/files/1428897/log.txt)

Here is the log, maybe you can find the problem

**Comment by stijnwop** [comment]
@DieModdingecke could you check if that check fixes your bug?
