### ISSUE TITLE
FS17_hoseSystem Script error .lua

### ISSUE THREAD

**Issue by litwa995** [stijnwop/hoseSystem#24]
Hi, I have the following problem with this mod.
After downloading these modifications:
**Fliegl STF 25000 VC
 Zunhammer SKE 18.5 PUD
Kotte FRC** for the Hosesystem.
When trying to connect a Hose to a barrel, I can not do anything, no description and also can not move.
Log in error such error:
**Error: Running LUA method 'update'.**
**C:/Users/Piotr/Documents/My Games/FarmingSimulator2017/mods/FS17_hoseSystem/specializations/HoseSystemPlayerInteractiveHandling.lua:64: invalid option '' to 'format'**

_Someone will help. Because the mod is cool, I'm also waiting for help :)_

**Comment by stijnwop** [comment]
You are playing on Polish i assume from the Modhub version?

There is a problem in the Polish translation format. 
modDesc.xml line 99 % should be %s

**Comment by litwa995** [comment]
Yes, I play Polish

**Comment by litwa995** [comment]
Where should be %s?

**Comment by stijnwop** [comment]
[modDesc.zip](https://github.com/stijnwop/hoseSystem/files/1444291/modDesc.zip)

Replace the modDesc from the HoseSystem with that modDesc.. that will fix the problem until i will release an update.

**Comment by litwa995** [comment]
ok, so i  will wait. thanks

**Comment by litwa995** [comment]
It's working with this modDesc. No problem, no error
