### ISSUE TITLE
Conflict with mod FS17_Ground_Modification

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [stijnwop/hoseSystem#27]
Hallo.
This mod does not work for your mod [(http://www.farming-simulator.com/mod.php?lang=en&country=ru&mod_id=75812&title=fs2017)]
If I add it to an existing game, I get an error `FS17_hoseSystem/specializations/HoseSystemRegister.lua:125: attempt to index field 'hoseSystemReferences' (a nil value)`.
And if I add these two mods at the same time, then hoses are not connected.

**Comment by cabmac** [comment]
that mod is causing problems everywhere with maps and mods... so, what is the best thing to do?

**Comment by stijnwop** [comment]
The bug is caused by the ground modification mod. The creator of that mod should do a fix.. so it's not up to me.

The error happens when you modified savegame data.. strange.. I could add an extra check tho.

**Comment by stijnwop** [comment]
Fixed the "cheated" savegame check.
The conflict is not mine to fix.

**Comment by Gonimy-Vetrom** [comment]
Thank you. Errors are no more. But they do not want to work together. :) We will work without a mod Ground_Modification. Maybe its author will fix it.
