### ISSUE TITLE
Error: Running LUA method 'update'.

### ISSUE THREAD

**Issue by knuuud** [stijnwop/hoseSystem#28]
This issue occurs when this mod is added , and the cause is a script Xentro has made for updating specifications on a upcomming mod. 
Error: Running LUA method 'update'.
H:/Dropbox/FarmingSimulator/Dedi17/FS17_hoseSystem/specializations/HoseSystemRegister.lua:212: attempt to index local 'specializationNames' (a nil value)
His answer was to add a check after line 211 
if specializationNames ~= nil then
but I can obviously not do that for every user that gets the conflict. Is this something you can add for the next update?

**Comment by stijnwop** [comment]
Mm, what script of Xentro are we talking about? So I can reproduce.

I sure can build in an extra check, no problem.

**Comment by knuuud** [comment]
It's a not yet released script. It's for having the possibility to release a mod with only standard giants specializations for consoles, and than this works as a PC addon where you can add custom scripts to the same machine without releasing it twice.

**Comment by stijnwop** [comment]
Alright, sounds interesting.
Will build in the check. ;)

**Comment by knuuud** [comment]
If it works as well in practice as in theory it will be a good way to get custom scripts on the machines without users having to edit them. It does the job here, but if Giants accepts the setup is a another matter 
Thanks :)

**Comment by stijnwop** [comment]
Commited the fix.
