### ISSUE TITLE
Hose system trouble 

### ISSUE THREAD

**Issue by criss20ster** [stijnwop/hoseSystem#31]
I have this trouble in my map 

HoseSystem [Warning] : HoseSystem is trying to load the fillTrigger XML file, but the file could not be found! Loading default fillTriggers..
HoseSystem [Warning] : HoseSystem is trying to load the fillTrigger XML file, but the file could not be found! Loading default fillTriggers..
HoseSystem [Warning] : HoseSystem is trying to load the fillTrigger XML file, but the file could not be found! Loading default fillTriggers..

**Comment by stijnwop** [comment]
This is normal and expected behaviour.. 

I will remove the "warning" since i get to much questions about it.
When a map doesn't support the hose system it will throw that warning. As it says at the end of the sentence that it's just loading the DEFAULT triggers.

**Comment by criss20ster** [comment]
So what should I understand that if I have such a message on the map then the hose system will not work for me?
