### ISSUE TITLE
Double input bug.

### ISSUE THREAD

**Issue by joska1232** [stijnwop/hoseSystem#37]
Im using this hose system mod and i found a problem here. when im using the STF 25000 VC and at the controls the game is showing 2 Y and 2 R button. now, the problem is: this is double input bug. I don't know why, but that won't work. I can't play without this mod because it makes the game more realistic.. please help me to solve it. That new update won't helped with it

**Comment by stijnwop** [comment]
You are playing the modhub version i assume? Cause it's been fixed a while ago (just use the github version). 
Currently working on an update for modhub.
