### ISSUE TITLE
incompatible with realistic beacon lights

### ISSUE THREAD

**Issue by Friendlyx** [stijnwop/hoseSystem#59]
D:/Farming Simulator 2017/Mods/FS17_hoseSystem/liquidManureHoses/3m/liquidManureHose3m.i3d (74.51) ms
Error: Running LUA method 'update'.
Mods/FS17_RealisticBeaconLights/VariableBeaconLights.lua:18: bad argument #1 to 'pairs' (table expected, got nil)

**Comment by Friendlyx** [comment]
after some research i found out thet this mod seams to be obsolate and the problem is that the script wants lights and in the hose there aren't any

**Comment by stijnwop** [comment]
Yeah that script should check if vehicles actually have lights before inserting stuff. So not up to me to fix but to the creator of that script. This is known for a long time if you read the readme. ;)
