### ISSUE TITLE
Docking support

### ISSUE THREAD

**Issue by stijnwop** [stijnwop/hoseSystem#6]
Write functionality to support manure docking.

FillArm
- [x] Create factory for creating strategies based on fillArm type (docking for example)
for being more future proof.

DockingArm
- [x] Search for dockingReferences (done by trigger)
- [x] Use in combination with the pump motor script
- [x] Support deformation on the docking reference (Funnel)
- [x] Forward manure to tanker when we have a frontdock. (#20) 

Connector
- [x] Create factory for creating connector strategies
- [x] Add docking reference support on the hoseSystem reference entries.
- [x] Move all coupling based logic in the base connector script to the coupling strategy

**Comment by Quintto** [comment]
Will this system work with the manure pack of monteur 1 from the mod hub?
http://www.farming-simulator.com/mod.php?lang=en&country=nl&mod_id=89464&title=fs2017

**Comment by stijnwop** [comment]
If he prepares the pack for it.. yes. Not up to me. ;)

**Comment by Quintto** [comment]
But his pack already has a docking system(complete with front dock and stuff) ,  would it be hard to make them compatible with each other?

**Comment by stijnwop** [comment]
Could be, i recall that those scripts are outdated (and perhaps not even MP ready). I did not check the package and probably never will.
I will support the docking feature for the HoseSystem.. as i said it's not up to me to make the package ready for it. I

t shouldn't be that much work tho.

And compatible would useless because all the main features from that pack are already supported in the Hose System.

**Comment by Quintto** [comment]
Damn Im jealous

**Comment by ForrestIT** [comment]
Is this function out for modders to implement or are you still tweeking and testing? Will you put out some sort of PDF explaining how to implement this docking funcion into your own mod? Really looking forward to having mods with it (adding it my self if i musst)!

**Comment by stijnwop** [comment]
You can use it when you run the development version. I am still working on some fixes and features. When finished i will try to write some information about the implementation process.. also will provide some example mods.

**Comment by stijnwop** [comment]
Included in latest release.
