### ISSUE TITLE
Lots of warnings in my log

### ISSUE THREAD

**Issue by SkinnyPoly** [stijnwop/hoseSystem#63]
I have used the Master file here 1.2. 
I seem to be getting a lot of warnings in my log.
Example:
HoseSystem [Warning] : The hoseSystemVehicle specialization in: FS17_Guellepack is outdated! Latest version is v1.2

My Slurry pack is the latest from Modhub 7.0.0.2
Everything seems to be working alright just warnings in my log.
Thanks!!

Attached log

[log.txt](https://github.com/stijnwop/hoseSystem/files/2346654/log.txt)

**Comment by stijnwop** [comment]
Hey, so by reading the warning you can clearly guess what that means..

If you don't want those warnings.. update the hoseSystemVehicle specialization.

**Comment by SkinnyPoly** [comment]
Hi, Thanks for the support and great addon/mod. 
For the next guy (_if he is a little slow like me_) that has these warnings: 

Take the HoseSystemVehicle.LUA file from the 1.2 hosesystem file and replace the HoseSystemVehicle.LUA in the mods file that is throwing the warning.
**Example:**
open the FS17_Guellepack with your zip program and drag the HoseSystemVehicle.LUA from 1.2 hosesystem into the Guellepack  -**scrite folder**- replacing the old HoseSystemVehicle.LUA

Thanks stijnwop. 
 I hope that is the correct process. Worked for me :)

**Comment by stijnwop** [comment]
Yes that's correct. ;)
